version: 1.0.0.alpha-{build}
nuget:
  account_feed: true
  project_feed: true
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: quiet
  project: DestinyPCL\DestinyPCL.csproj