version: 1.0.0.Daily-{build}
os: Visual Studio 2015

nuget:  
  project_feed: true

before_build:
- ps: nuget update -self.
- ps: nuget restore
build:
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: quiet
