
version: 0.0.1.{build}a-dev
branches:
  only:
  - master
os: Visual Studio 2015
skip_non_tags: true



assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:  
  project_feed: true

before_build:
- ps: nuget update -self.
- ps: nuget restore
build:
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: quiet

deploy:
  provider: NuGet
  api_key: 
    secure: +0yHx/WVNuXWa1QoDjwGq/+0o/PpQXTa1QgP/CjnU+1ZaszN+O3EEMYYL93/6dqA
  skip_symbols: true
  artifact: /.*\.nupkg/
