version: 1.0.0.{build}-dev
os: Visual Studio 2015

nuget:  
  project_feed: true

before_build:
- ps: nuget update -self.
- ps: nuget restore
build:
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: quiet

test: off

deploy:
  provider: NuGet
  api_key: 
  secure: +0yHx/WVNuXWa1QoDjwGq/+0o/PpQXTa1QgP/CjnU+1ZaszN+O3EEMYYL93/6dqA
  skip_symbols: true
  artifact: /.*\.nupkg/